Documentation:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: 'expanded'
Metrics/BlockLength:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/StringLiterals:
  Enabled: false