Documentation:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: 'expanded'
Metrics/BlockLength:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Layout/SpaceInsideBrackets:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20